// POST /api/generate — trigger AI selection pipeline.
// On Cloudflare Pages (edge), generation is not possible (no fs).
// Data is generated by GitHub Actions (daily-picker.yml) and committed to .data/.
// On local dev (Node.js), this route runs in Node.js and can generate data.
export const runtime = "edge";

import { NextResponse } from "next/server";

export const maxDuration = 300;

export async function POST(request: Request) {
  return NextResponse.json({
    ok: false,
    error: "Generation is done by GitHub Actions (daily-picker.yml). On Cloudflare Pages, data is read-only.",
  }, { status: 405 });
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  if (searchParams.get("action") === "seed") {
    return NextResponse.json({
      ok: false,
      error: "Seeding is done by GitHub Actions or local dev. On Cloudflare Pages, data is read-only.",
    });
  }
  return NextResponse.json({ ok: false, error: "use POST" }, { status: 405 });
}
